### ISSUE TITLE
您好，能不能详细讲讲这个如何配置

### ISSUE THREAD

**Issue by MuMuloveU** [snow-sprite/wx-bot#1]
export WECHATY_PUPPET=wechaty-puppet-wechat // 关键，需要配置你使用的puppet

**Comment by snow-sprite** [comment]
我用这个只是基于web的Angular hook api，还有其他的。详细看下官方文档吧：https://github.com/wechaty/wechaty#1-class-wechaty

**Comment by snow-sprite** [comment]
> export WECHATY_PUPPET=wechaty-puppet-wechat // 关键，需要配置你使用的puppet

我用这个只是基于web的Angular hook api，还有其他的。详细看下官方文档吧：https://github.com/wechaty/wechaty#1-class-wechaty

**Comment by MuMuloveU** [comment]
ok,感谢
